
server {
	listen 8080;
	host 0.0.0.0;

	server_name exemple.com hamid.com;
	client_max_body_size 1m;
	error_page 404 error_pages/404.html;

	root ./html;
    location / {
		methods POST GET DELETE;
        index index.html;
        autoindex on;
        cgi_pass .php /usr/bin/php-cgi;

    }
    location /upload {
		methods POST GET DELETE;
        index index.html;
        upload_path html/upload;
    }

    location /redirect {
        return 301 http://www.google.com;
    }

    location /cgi-bin {
		methods POST GET DELETE;
        index index.php;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .sh /bin/bash;
        autoindex on;
    }
}
