server {
    listen 8080;
    # host localhost;
    # host 127.0.1.1;
    host 0.0.0.0;

    server_name exemple.com hamid.com;
    
    # Caps payload sizes (Tested by the 2MB payload test -> returns 413)
    client_max_body_size 1m;
    
    # Fixed the path based on your 'find .' output
    error_page 404 error_pages/not_found_404.html;

    root ./www ;

    # Default route (Tests 1, 2, 3, 4, 7, 10)
    # Only allows GET and DELETE. POSTing here will return 405 Method Not Allowed.
    location / {
        root ./www;
        methods GET DELETE;
        autoindex on;
    }

    # Restored /abc because the RAW chunked and smuggling tests use /abc/chunk.txt
    location /abc {
        methods GET POST DELETE;
        root ./www/uploads;
        index index.html;
        upload_path ./www/uploads/storage;
    }

    location /test1 {
        methods GET POST DELETE;
        root ./www/uploads;
        index index.html;
        upload_path ./www/uploads/storage;
    }

    # Test 12.1: Rejects DELETE -> returns 405 Method Not Allowed
    location /test2 {
        methods GET POST; 
        root ./www/uploads;
        index index.html;
        upload_path ./www/uploads/storage;
    }

    # Test 12.2: Allows DELETE -> returns 204 No Content
    location /test3 {
        methods GET POST DELETE;
        root ./www/uploads;
        index index.html;
        upload_path ./www/uploads/storage;
    }

    # CGI execution (Allows GET/POST. DELETE returns 405)
    location /cgi {
        methods GET POST;
        cgi_pass .py /usr/bin/python3;
    }

    # Redirections
    location /ancienne-page {
        return 301 /index.html;
    }

    location /google {
        return 301 https://google.com;
    }

    location /hamid {
        return 301 https://youtube.com;
    }
}
