server {
    listen 8080;
    host 0.0.0.0;
    root ./www;
    index index.htm;
    autoindex on;

    location / {
        methods GET DELETE;
        autoindex on;
    }

    location /upload {
        methods GET POST DELETE;
        upload_path ./www/uploads/storage;
    }

    location /cgi {
        methods GET POST;
        cgi_pass .py /usr/bin/python3;
    }
}
