server {
    listen 8080;                        # Port d'écoute
    host 127.0.0.1;                     # Interface (hôte)
    server_name exemple.com;            # Nom du serveur
    client_max_body_size 1M;            # Limite pour les uploads (1 Mo)
    
    error_page 404 error_pages/404.html; # Pages d'erreur personnalisées

    # Route pour les fichiers statiques
    location / {
        root ./www;                     # Répertoire racine
        methods GET;                    # Méthodes autorisées
        index index.html;               # Fichier par défaut
        autoindex on;                   # Listing des fichiers activé
    }

    # Route spécifique pour les uploads
    location /uploads {
        methods GET POST DELETE;
        root ./www/uploads;
        upload_path ./www/uploads/storage; # Où stocker les fichiers reçus
    }

    # Route pour le CGI (ex: Python)
    location .py {
        methods GET POST;
        cgi_path /usr/bin/python3;      # Chemin vers l'exécutable CGI
    }

    # Redirection
    location /ancienne-page {
        return 301 /index.html;
    }
}

server {
    listen 9090;
    host 0.0.0.0;
    server_name test.com;
    # ... autre configuration pour un second serveur
}
