server {
	host localhost;
  listen 1025;
	listen 1026;
	server_name localhost;
	root EngineX/www;
	index index.htm;
	autoindex on;
	client_max_body_size 2k;

	methods GET POST DELETE;

	location / {
		methods GET POST DELETE;
	}

	location / {
        cgi_pass .py python3;
    }
	location /upload{
		methods GET POST DELETE;
	}
	location /get-only {
		methods GET;
	}
	location /post-only {
		methods POST;
	}
	location /old-page {
       return 301 /new-page;
    }
	location /temp-page {
		return 302 /index.htm;
	}
	location /ext-redirect {
		return 301 http://example.com;
	}

	location /autoindex-dir {
		autoindex  on;
	}
	
	location /no-index-dir {
		autoindex  off;
	}

	location /auto-with-index {
		autoindex  on;
		index      index.htm;
	}

	location /mapped {
		root EngineX/www/root-Test;
    	index index.htm;
	}
	location /dir-with-index { 
		root EngineX/www;
		index index.htm;
	}
	location /cgi-bin {
		cgi_pass .py python3;
		methods POST GET;
	}

}

server {
	host localhost;
	listen 1027;
	methods GET;
	root EngineX/www-subject-tester;
	index index.htm;
	autoindex on;

    location /directory/Yeah/ {
		index youpi.bad_extension;
	}

	location /post_body {
		client_max_body_size 100;
		methods POST;
	}

	location /directory/ {
		
	}

	location /directory_get/ {
		root EngineX/www-subject-tester/YoupiBanane;
		index youpi.bad_extension;
		methods GET;
	}

	location /directory_post/ {
		cgi_pass .bla EngineX/www-subject-tester/cgi_tester;
		methods POST;
	}
}
